# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'thamespipeline'
    subscriptionId: 'afdc32d4-a9f7-4ea6-9bff-e8c5aa1ed52f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'deployments'
    location: 'UK South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/duddit2/Thames-Veeam/master/storageWithFileShares.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/duddit2/Thames-Veeam/master/sa01.parameters.json'
    deploymentMode: 'Incremental'